[custom.all.indexed-graph]
type   = "local"
path   = "."
ipkg   = "indexed-graph.ipkg"

[custom.all.indexed-graph-profile]
type   = "local"
path   = "profile"
ipkg   = "indexed-graph-profile.ipkg"

[custom.all.array]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-array"
commit = "latest:main"
ipkg   = "array.ipkg"

